<a href="https://colab.research.google.com/github/SeunginKimT/Data-Analysis/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
print(np.array([1,2,3]))

[1 2 3]


In [3]:
import numpy
print(numpy.array([1,2,3]))

[1 2 3]


In [4]:
import numpy as np

arr_1 = np.array([1,2,3,4,5])
print(arr_1)

[1 2 3 4 5]


In [5]:
arr_1 * 2

array([ 2,  4,  6,  8, 10])

In [6]:
arr_1

array([1, 2, 3, 4, 5])

In [9]:
import numpy as np #파이썬 리스트를 ndarray로 변환
# 2차원 배열은 표 table, matrix, 행렬
# 가로 행 row, 세로 열 column
arr_2 = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]]
)
print(arr_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
#3차원 배열은 cube, volume
import numpy as np

arr_3 = np.array([[[1,2,3],
                   [4,5,6]],
                  [[7,8,9],
                  [10,11,12]],
                [[13,14,15],
                 [16,17,18]]])
print(arr_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [13]:
import numpy as np

print(np.array([1,2,3]).dtype)

int64


In [14]:
print(np.array([1,2,3], dtype = 'int8').dtype)

int8


In [15]:
print(np.array([1,2,3], dtype = 'i1').dtype)

int8
